# Generated by Django 4.1.2 on 2022-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('categories', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('quatity', models.IntegerField(default=1)),
                ('for_sale', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('review', models.TextField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=20)),
            ],
        ),
    ]
